# Generated by Django 4.2.3 on 2023-07-14 18:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0002_user_is_active_user_is_staff"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
    ]
