# Generated by Django 4.2.3 on 2023-07-21 09:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0005_remove_user_profile_pic_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="Address",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="DoB",
            field=models.DateField(
                editable=False, max_length=150, null=True, verbose_name="Date of Birth"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="Gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female")],
                default="Prefer not to say",
                max_length=150,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="bio",
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="company_organization",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="job_title",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="phone_number",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="username",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(null=True, upload_to="img"),
        ),
    ]
